version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: warehouse_postgres
    environment:
      POSTGRES_DB: warehouse_bloom
      POSTGRES_USER: warehouse_user
      POSTGRES_PASSWORD: warehouse_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - warehouse_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: warehouse_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - warehouse_network

  # Backend Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: warehouse_server
    environment:
      PORT: 4000
      DATABASE_URL: postgresql://warehouse_user:warehouse_pass@postgres:5432/warehouse_bloom
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRES_IN: 7d
      CLIENT_ORIGIN: http://localhost:8080
      NODE_ENV: production
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis
    networks:
      - warehouse_network
    volumes:
      - ./server:/app
      - /app/node_modules

  # Frontend Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: warehouse_client
    environment:
      VITE_API_BASE_URL: http://localhost:4000/api
      VITE_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - server
    networks:
      - warehouse_network
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  postgres_data:
  redis_data:

networks:
  warehouse_network:
    driver: bridge