// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjhuuccpqdgaoakggwoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqaHV1Y2NwcWRnYW9ha2dnd29qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMzg0MDgsImV4cCI6MjA3MzkxNDQwOH0.zmRGNAVx4aNGbw7-y1EmahPdEikVyFc8Mcz6J6O_mJ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});